/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyshop;

import DAO.khachhangDAO;
import java.util.List;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.KhachHang;

/**
 *
 * @author ADMIN
 */
public class QuanLyKhachHang extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyKhachHang
     */
    private final DefaultTableModel tbModelkhachhang = new DefaultTableModel();
    public QuanLyKhachHang() {
        initComponents();
        Showdatakhachhang();
        btnThucHien.setEnabled(false);
    }
    public void cleardatakhachhang()
    {
        while (tbModelkhachhang.getRowCount()>0) {
            tbModelkhachhang.removeRow(0);
            
        }
    }
    private void Showdatakhachhang()
    {
        String[] tencot = {"Mã Khách Hàng", "Họ Tên", "Năm Sinh", "Địa Chỉ", "Số Điện Thoai"};
        tbModelkhachhang.setColumnIdentifiers(tencot);
        tbkhachhang.setModel(tbModelkhachhang);
        cleardatakhachhang();
        khachhangDAO nv = new khachhangDAO ();
        List<KhachHang> data = nv.getKhachHang();
        for (int i = 0; i < data.size(); i++) {
            String[] row = {
                String.valueOf(data.get(i).getMakh()),
                data.get(i).getTenkh(),
                String.valueOf(data.get(i).getNamsinh()),
                data.get(i).getDiachi(),
                data.get(i).getSodienthoai(),               
            };
            tbModelkhachhang.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbkhachhang = new javax.swing.JTable();
        txtmakh = new javax.swing.JTextField();
        txttenkh = new javax.swing.JTextField();
        txtnamsinh = new javax.swing.JTextField();
        txtsdt = new javax.swing.JTextField();
        txtdiachi = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        btnThem = new javax.swing.JButton();
        btnsua = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btntk = new javax.swing.JButton();
        btnThucHien = new javax.swing.JButton();
        btnlammoi = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Quản Lý Khách Hàng");

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back-icon.png"))); // NOI18N
        jLabel2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel2MouseClicked(evt);
            }
        });

        tbkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4", "Title 5"
            }
        ));
        tbkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbkhachhangMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbkhachhang);

        jLabel3.setText("Mã Khách Hàng");

        jLabel4.setText("Tên Khách Hàng");

        jLabel5.setText("Năm Sinh");

        jLabel6.setText("Địa Chỉ");

        jLabel7.setText("Số Điện Thoại");

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Chức Năng"));

        btnThem.setText("Thêm");
        btnThem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThemActionPerformed(evt);
            }
        });

        btnsua.setText("Sửa");
        btnsua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnsuaActionPerformed(evt);
            }
        });

        btnxoa.setText("Xóa");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        btntk.setText("Tìm Kiếm");
        btntk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntkActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnThem, javax.swing.GroupLayout.DEFAULT_SIZE, 80, Short.MAX_VALUE)
                    .addComponent(btnxoa, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btntk, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnsua, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(18, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(20, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnThem)
                    .addComponent(btnsua))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnxoa)
                    .addComponent(btntk))
                .addGap(18, 18, 18))
        );

        btnThucHien.setText("Thực Hiện");
        btnThucHien.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnThucHienActionPerformed(evt);
            }
        });

        btnlammoi.setText("Làm Mới");
        btnlammoi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnlammoiActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(296, 296, 296)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 494, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(57, 57, 57)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 170, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmakh, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtnamsinh, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap())
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnlammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnThucHien, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(11, 11, 11))
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(56, 56, 56))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1))
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 66, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 354, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtmakh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtnamsinh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnThucHien, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnlammoi, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(12, 12, 12))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnsuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnsuaActionPerformed
        // TODO add your handling code here:
        btnThucHien.setEnabled(true);
        btnThem.setEnabled(false);
        btnxoa.setEnabled(false);
        btntk.setEnabled(false);
        txtmakh.setEditable(false);
    }//GEN-LAST:event_btnsuaActionPerformed

    private void jLabel2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel2MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        HeThong ht = new HeThong();
        ht.setLocationRelativeTo(null);
        ht.setVisible(true);
    }//GEN-LAST:event_jLabel2MouseClicked

    private void btnThemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThemActionPerformed
        // TODO add your handling code here:
        txtmakh.setEditable(false);
        btnThucHien.setEnabled(true);
        btnsua.setEnabled(false);
        btnxoa.setEnabled(false);
        btntk.setEnabled(false);
    }//GEN-LAST:event_btnThemActionPerformed

    private void btnlammoiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnlammoiActionPerformed
        // TODO add your handling code here:
        btnThucHien.setEnabled(false);
        btnThem.setEnabled(true);
        btnsua.setEnabled(true);
        btntk.setEnabled(true);
        btnxoa.setEnabled(true);
        txtmakh.setText("");
        txttenkh.setText("");
        txtdiachi.setText("");
        txtnamsinh.setText("");
        txtsdt.setText("");
        txtmakh.setEditable(true);
        txttenkh.setEditable(true);
        txtdiachi.setEditable(true);
        txtsdt.setEditable(true);
        txtnamsinh.setEditable(true);
        Showdatakhachhang();
    }//GEN-LAST:event_btnlammoiActionPerformed

    private void tbkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbkhachhangMouseClicked
        // TODO add your handling code here:
        int row = tbkhachhang.getSelectedRow();
        if(row >= 0)
        {
            txtmakh.setText(tbkhachhang.getValueAt(row, 0).toString());
            txttenkh.setText(tbkhachhang.getValueAt(row, 1).toString());
            txtnamsinh.setText(tbkhachhang.getValueAt(row, 2).toString());
            txtdiachi.setText(tbkhachhang.getValueAt(row, 3).toString());
            txtsdt.setText(tbkhachhang.getValueAt(row, 4).toString());
        }
    }//GEN-LAST:event_tbkhachhangMouseClicked

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        btnThucHien.setEnabled(true);
        btnsua.setEnabled(false);
        btnThem.setEnabled(false);
        btntk.setEnabled(false);
        txttenkh.setEditable(false);
        txtdiachi.setEditable(false);
        txtsdt.setEditable(false);
        txtnamsinh.setEditable(false);
    }//GEN-LAST:event_btnxoaActionPerformed

    private void btntkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntkActionPerformed
        // TODO add your handling code here:
        btnThucHien.setEnabled(true);
        btnsua.setEnabled(false);
        btnThem.setEnabled(false);
        btnxoa.setEnabled(false);
        txtmakh.setEditable(false);
        txtdiachi.setEditable(false);
        txtsdt.setEditable(false);
        txtnamsinh.setEditable(false);
    }//GEN-LAST:event_btntkActionPerformed

    private void btnThucHienActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnThucHienActionPerformed
        // TODO add your handling code here:
        if(btnThem.isEnabled())
        {            
            try {
                String Name_PATTERN = "^[\\p{L}\\p{M}' \\.\\-]+$";
                Pattern p = Pattern.compile(Name_PATTERN);
                if(p.matcher(txttenkh.getText()).find()){
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Tên chỉ bao gồm chữ cái, xin nhập lại Tên Nhân Viên");
                    return;
                }
                
                
                try {
                    int n = Integer.parseInt(txtsdt.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại chỉ bao gồm chữ số, xin hãy nhập lai!");
                    return;
                }
                if(txtsdt.getText().length()>10 || txtsdt.getText().length()<10){
                    JOptionPane.showMessageDialog(this, "Số điện thoại phải có 10 số");
                    return;
                }
                try {
                    int n = Integer.parseInt(txtnamsinh.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "xin hãy nhập lai năm sinh VD:2002!");
                    return;
                }
                
                KhachHang kh = new KhachHang();
                kh.setTenkh(txttenkh.getText());
                kh.setNamsinh(txtnamsinh.getText());
                kh.setDiachi(txtdiachi.getText());
                kh.setSodienthoai(txtsdt.getText());
                khachhangDAO KHDAO = new khachhangDAO();
                KHDAO.insert(kh);
                JOptionPane.showMessageDialog(this, "Them moi thanh cong");
                Showdatakhachhang();
                
            } catch (Exception e) {
//                if(e.getMessage().equals("Duplicate entry '"+txtMaNV.getText()+"' for key 'PRIMARY'")){
//                    JOptionPane.showMessageDialog(this, "Mã nhân viên đã tồn tại vui lòng nhập lại");
//                }
                System.err.println("Loi:" + e.getMessage());
            }
        }else if(btnsua.isEnabled()){
                
            try {
                String Name_PATTERN = "^[\\p{L}\\p{M}' \\.\\-]+$";
                Pattern p = Pattern.compile(Name_PATTERN);
                if(p.matcher(txttenkh.getText()).find()){
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Tên chỉ bao gồm chữ cái, xin nhập lại Tên Nhân Viên");
                    return;
                }
                
                
                try {
                    int n = Integer.parseInt(txtsdt.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Số điện thoại chỉ bao gồm chữ số, xin hãy nhập lai!");
                    return;
                }
                if(txtsdt.getText().length()>10 || txtsdt.getText().length()<10){
                    JOptionPane.showMessageDialog(this, "Số điện thoại phải có 10 số");
                    return;
                }
                try {
                    int n = Integer.parseInt(txtnamsinh.getText());
                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "xin hãy nhập lai năm sinh VD:2002!");
                    return;
                }
                
                KhachHang kh = new KhachHang();
                kh.setMakh(Integer.valueOf(txtmakh.getText()));
                kh.setTenkh(txttenkh.getText());
                kh.setNamsinh(txtnamsinh.getText());
                kh.setDiachi(txtdiachi.getText());
                kh.setSodienthoai(txtsdt.getText());
                khachhangDAO KHDAO = new khachhangDAO();
                               
                KHDAO.update(kh);
                JOptionPane.showMessageDialog(this, "Sua thanh cong");
                Showdatakhachhang();
            } catch (Exception e) {
                System.out.println(e.getMessage());
                e.printStackTrace();
            }
        }else if(btnxoa.isEnabled()){
            String ml = String.valueOf(txtmakh.getText());
            StringBuilder sb = new StringBuilder();
            if(ml.equals("")){
                JOptionPane.showMessageDialog(this, "Mã khách hàng không được trống");
            }
            else{
                 khachhangDAO KHDAO = new khachhangDAO();
                boolean kt = KHDAO.delete(Integer.valueOf(ml));
                if(kt==true)
                {
                    JOptionPane.showMessageDialog(this, "Xoa thanh cong");
                }else{
                    JOptionPane.showMessageDialog(this, "Xoa that bai");
                }
                Showdatakhachhang();
            }
        }else if(btntk.isEnabled()){
            String Name_PATTERN = "^[\\p{L}\\p{M}' \\.\\-]+$";
                Pattern p = Pattern.compile(Name_PATTERN);
                if(p.matcher(txttenkh.getText()).find()){
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Tên chỉ bao gồm chữ cái, xin nhập lại Tên Nhân Viên");
                    return;
                }
            try {
                cleardatakhachhang();
                khachhangDAO dao = new khachhangDAO();
                List<KhachHang> data = dao.Search(txttenkh.getText());
                for (int i = 0; i < data.size(); i++) {
                    String[] row = {
                        String.valueOf(data.get(i).getMakh()),
                        data.get(i).getTenkh(),
                        data.get(i).getNamsinh(),
                        data.get(i).getDiachi(),
                        data.get(i).getSodienthoai(),                
                    };
                    tbModelkhachhang.addRow(row);

                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, "Khách Hàng không tồn tại Khong Ton Tai");

            }
        }
    }//GEN-LAST:event_btnThucHienActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyKhachHang.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyKhachHang().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnThem;
    private javax.swing.JButton btnThucHien;
    private javax.swing.JButton btnlammoi;
    private javax.swing.JButton btnsua;
    private javax.swing.JButton btntk;
    private javax.swing.JButton btnxoa;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbkhachhang;
    private javax.swing.JTextField txtdiachi;
    private javax.swing.JTextField txtmakh;
    private javax.swing.JTextField txtnamsinh;
    private javax.swing.JTextField txtsdt;
    private javax.swing.JTextField txttenkh;
    // End of variables declaration//GEN-END:variables
}
