/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyshop;

import DAO.cthoadonDAO;
import DAO.hoadonDAO;
import DAO.khachhangDAO;
import DAO.quanaoDAO;
import java.io.Console;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import model.KhachHang;
import model.QuanAo;
import model.TaiKhoan;
import model.ctHoaDon;
import model.tthoadon;
import org.apache.poi.xwpf.usermodel.XWPFDocument;
import org.apache.poi.xwpf.usermodel.XWPFParagraph;
import org.apache.poi.xwpf.usermodel.XWPFRun;

/**
 *
 * @author ADMIN
 */
public class QuanLyHoaDon extends javax.swing.JFrame {
    private final DefaultTableModel tbModelkhachhang = new DefaultTableModel();
     private final DefaultTableModel tbModelquanao = new DefaultTableModel();
     private final DefaultTableModel tbModelcthoadon = new DefaultTableModel();
     private final DefaultTableModel tbModelhoadon = new DefaultTableModel();
    /**
     * Creates new form QuanLyHoaDon
     */
    public QuanLyHoaDon() {
        initComponents();
        Showdata();
        Showdatakhachhang();
        Showdatahd();
        Showdatacthd();
        TaiKhoan tk = new TaiKhoan();
        txtmanv.setText(tk.getUsername());
        btntaohd.setEnabled(false);
        btnxoahd.setEnabled(false);
        btnxuathd.setEnabled(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtten = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtdiachi = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtsdt = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtmanv = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbcthoadon = new javax.swing.JTable();
        txtdate = new com.toedter.calendar.JDateChooser();
        txttongtien1 = new javax.swing.JLabel();
        txttongtien = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        txttenkh = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tkkh = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbkhachhang = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        txtqa = new javax.swing.JTextField();
        tkqa = new javax.swing.JButton();
        btntk1 = new javax.swing.JComboBox<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        tbquanao = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        txtmaqa = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        txtsoluong = new javax.swing.JTextField();
        btnthem = new javax.swing.JButton();
        btnxoa = new javax.swing.JButton();
        btntaohd = new javax.swing.JButton();
        btnhuy = new javax.swing.JButton();
        btnxoahd = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        tbhoadon = new javax.swing.JTable();
        btnxuathd = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Hóa Đơn"));

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Khách Hàng"));

        jLabel1.setText("Tên Khách Hàng:");

        txtten.setText("...");

        jLabel3.setText("Địa Chỉ:");

        txtdiachi.setText("...");

        jLabel5.setText("SĐT:");

        txtsdt.setText("...");

        jLabel6.setText("Mã Nhân Viên:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap(54, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsdt, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtmanv, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(20, 20, 20))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtten, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtdiachi, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtsdt))
                .addGap(5, 5, 5)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtmanv))
                .addContainerGap())
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Thông Tin Hóa Đơn"));

        tbcthoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbcthoadon.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                tbcthoadonMouseMoved(evt);
            }
        });
        tbcthoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbcthoadonMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tbcthoadon);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtdate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(txtdate, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 194, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txttongtien1.setText("...");

        txttongtien.setText("Tổng Tiền:");

        jLabel9.setText("VNĐ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttongtien1, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(33, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttongtien1)
                    .addComponent(txttongtien)
                    .addComponent(jLabel9))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Khách Hàng"));

        txttenkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txttenkhActionPerformed(evt);
            }
        });

        jLabel8.setText("Tên Khách Hàng");

        tkkh.setText("Tìm Kiếm");
        tkkh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkkhActionPerformed(evt);
            }
        });

        tbkhachhang.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbkhachhang.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbkhachhangMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(tbkhachhang);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel8)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, 121, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(tkkh)))
                .addContainerGap(19, Short.MAX_VALUE))
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txttenkh, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tkkh))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder("Quần Áo"));

        tkqa.setText("Tìm Kiếm");
        tkqa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tkqaActionPerformed(evt);
            }
        });

        btntk1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Theo Mã", "Theo Tên", "Theo Hãng", " " }));

        tbquanao.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbquanao.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbquanaoMouseClicked(evt);
            }
        });
        jScrollPane3.setViewportView(tbquanao);

        jLabel2.setText("Mã Quần Áo:");

        jLabel4.setText("Số Lượng:");

        btnthem.setText("Thêm Vào");
        btnthem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthemActionPerformed(evt);
            }
        });

        btnxoa.setText("Loại Bỏ");
        btnxoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                        .addContainerGap(18, Short.MAX_VALUE)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 236, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btntk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel5Layout.createSequentialGroup()
                                .addComponent(txtqa, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(tkqa)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnxoa)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtmaqa, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnthem)
                        .addGap(16, 16, 16))))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(btntk1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtqa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tkqa))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 274, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(txtmaqa, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtsoluong, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnthem)
                    .addComponent(btnxoa))
                .addGap(24, 24, 24))
        );

        btntaohd.setText("Tạo Hóa Dơn");
        btntaohd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btntaohdActionPerformed(evt);
            }
        });

        btnhuy.setText("Trở lại");
        btnhuy.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnhuyActionPerformed(evt);
            }
        });

        btnxoahd.setText("Hủy Hóa Đơn");
        btnxoahd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxoahdActionPerformed(evt);
            }
        });

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh Sách hóa đơn"));

        tbhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tbhoadon.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tbhoadonMouseClicked(evt);
            }
        });
        jScrollPane4.setViewportView(tbhoadon);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 641, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(39, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 96, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnxuathd.setText("Xuất Hóa Đơn");
        btnxuathd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuathdActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(19, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(107, 107, 107))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnhuy)
                        .addGap(85, 85, 85)
                        .addComponent(btntaohd)
                        .addGap(77, 77, 77)
                        .addComponent(btnxoahd)
                        .addGap(54, 54, 54)
                        .addComponent(btnxuathd)
                        .addGap(183, 183, 183))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btntaohd)
                    .addComponent(btnxoahd)
                    .addComponent(btnhuy)
                    .addComponent(btnxuathd))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txttenkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txttenkhActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txttenkhActionPerformed

    private void btnhuyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnhuyActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        HeThong ht = new HeThong();
        ht.setLocationRelativeTo(null);
        ht.setVisible(true);
    }//GEN-LAST:event_btnhuyActionPerformed

    private void tkkhActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkkhActionPerformed
        // TODO add your handling code here:
        String Name_PATTERN = "^[\\p{L}\\p{M}' \\.\\-]+$";
                Pattern p = Pattern.compile(Name_PATTERN);
                if(p.matcher(txttenkh.getText()).find()){
                    
                }else{
                    JOptionPane.showMessageDialog(this, "Tên chỉ bao gồm chữ cái, xin nhập lại Tên Nhân Viên");
                    return;
                }
            try {
                cleardatakhachhang();
                khachhangDAO dao = new khachhangDAO();
                List<KhachHang> data = dao.Search(txttenkh.getText());
                for (int i = 0; i < data.size(); i++) {
                    String[] row = {
                        String.valueOf(data.get(i).getMakh()),
                        data.get(i).getTenkh(),
                        data.get(i).getNamsinh(),
                        data.get(i).getDiachi(),
                        data.get(i).getSodienthoai(),                
                    };
                    tbModelkhachhang.addRow(row);

                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
                JOptionPane.showMessageDialog(this, "Khách Hàng không tồn tại Khong Ton Tai");

            }
    }//GEN-LAST:event_tkkhActionPerformed

    private void tkqaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tkqaActionPerformed
        // TODO add your handling code here:
        if(btntk1.getSelectedItem()=="Theo Mã"){
                if(txtqa.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Mã quần áo không được trống");
                    return;
                }else{
                    try {
                    cleardata();
                    quanaoDAO ins = new quanaoDAO();
                    List<QuanAo> data = ins.SearchByMa(Integer.valueOf(txtqa.getText()));
                    for (int i = 0; i < data.size(); i++) {
                        String[] row = {
                            String.valueOf(data.get(i).getMaqa()),
                            data.get(i).getTenqa(),

                            data.get(i).getHang(),
                            String.valueOf(data.get(i).getGia()),
                            String.valueOf(data.get(i).getSoluong()),
                            
                        };
                        tbModelquanao.addRow(row);

                    }
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                        JOptionPane.showMessageDialog(this, "Mã quần áo không tồn tại Khong Ton Tai");

                    }
                }
                
                
            }else if(btntk1.getSelectedItem()=="Theo Tên"){
                if(txtqa.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Tên quần áo không được trống");
                    return;
                }else{
                    try {
                    cleardata();
                    quanaoDAO ins = new quanaoDAO();
                    List<QuanAo> data = ins.SearchByTen(txtqa.getText());
                    for (int i = 0; i < data.size(); i++) {
                        String[] row = {
                            String.valueOf(data.get(i).getMaqa()),
                            data.get(i).getTenqa(),

                            data.get(i).getHang(),
                            String.valueOf(data.get(i).getGia()),
                            String.valueOf(data.get(i).getSoluong()),
                            
                        };
                        tbModelquanao.addRow(row);

                    }
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                        JOptionPane.showMessageDialog(this, "Tên quần áo không tồn tại Khong Ton Tai");

                    }
                }
            }else if(btntk1.getSelectedItem()=="Theo Hãng"){
                if(txtqa.getText().equals("")){
                    JOptionPane.showMessageDialog(this, "Hãng quần áo không được trống");
                    return;
                }else{
                    try {
                    cleardata();
                    quanaoDAO ins = new quanaoDAO();
                    List<QuanAo> data = ins.SearchByHang(txtqa.getText());
                    for (int i = 0; i < data.size(); i++) {
                        String[] row = {
                            String.valueOf(data.get(i).getMaqa()),
                            data.get(i).getTenqa(),

                            data.get(i).getHang(),
                            String.valueOf(data.get(i).getGia()),
                            String.valueOf(data.get(i).getSoluong()),
                            
                        };
                        tbModelquanao.addRow(row);

                    }
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                        JOptionPane.showMessageDialog(this, "Hãng quần áo không tồn tại Khong Ton Tai");

                    }
                }
            }
    }//GEN-LAST:event_tkqaActionPerformed

    private void tbkhachhangMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbkhachhangMouseClicked
        // TODO add your handling code here:
        int row = tbkhachhang.getSelectedRow();
        if(row >= 0)
        {
            txtten.setText(tbkhachhang.getValueAt(row, 1).toString());
            txtdiachi.setText(tbkhachhang.getValueAt(row, 2).toString());
            txtsdt.setText(tbkhachhang.getValueAt(row, 3).toString());
        }
        btntaohd.setEnabled(true);
        btnxoahd.setEnabled(true);
    }//GEN-LAST:event_tbkhachhangMouseClicked

    private void btnthemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthemActionPerformed
        // TODO add your handling code here:
        if(txtmaqa.getText().equals("") || txtsoluong.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
            return;
        }
        try {
            int n = Integer.parseInt(txtsoluong.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "xin hãy nhập lai số lượng!");
            return;
        }
        try {
                quanaoDAO ins = new quanaoDAO();
                QuanAo qa = new QuanAo();
                int row = tbquanao.getSelectedRow();
                int maqa = Integer.valueOf(txtmaqa.getText());
                int soluongthem = Integer.valueOf(txtsoluong.getText());
                int soluongcon = ins.getsoluong(maqa);
                int soluongconlai = soluongcon - soluongthem; 
                System.out.println(soluongthem+"/"+soluongcon+"/"+soluongconlai);
                if(soluongconlai<0){
                    JOptionPane.showMessageDialog(this, "Số Lượng quần áo không đủ, số lượng còn"+soluongcon);
                    return;
                }else{
                    ins.updatesl(soluongconlai, maqa);
                }
            } catch (Exception e) {
                System.out.println(e.getMessage());
                e.printStackTrace();
            }
        try {
                ctHoaDon kh = new ctHoaDon();
                int row = tbhoadon.getSelectedRow();
                if(row >= 0)
                {
                    kh.setMahd(Integer.valueOf(tbhoadon.getValueAt(row, 0).toString()));
                    System.out.println(Integer.valueOf(tbhoadon.getValueAt(row, 0).toString()));
                }
                int row2 = tbquanao.getSelectedRow();
                if(row2 >= 0)
                {
                    kh.setMaqa(Integer.valueOf((tbquanao.getValueAt(row2, 0).toString())));
                    kh.setTenqa((tbquanao.getValueAt(row2, 1).toString()));
                    kh.setGia(Float.valueOf(tbquanao.getValueAt(row2, 3).toString()));
                }
                kh.setSoluong(Integer.valueOf(txtsoluong.getText()));
                System.out.println(tbquanao.getValueAt(row2, 1).toString());
                cthoadonDAO cthd = new  cthoadonDAO();
                cthd.insert(kh);
                JOptionPane.showMessageDialog(this, "Them moi thanh cong");
                Showdatacthd();
        } catch (Exception e) {
            System.out.println(e);
        }
        try {
                int row = tbhoadon.getSelectedRow();
                int mahd = Integer.valueOf(tbhoadon.getValueAt(row, 0).toString());
                cthoadonDAO ins = new cthoadonDAO();
                float tonggia = ins.getGia(mahd);
                hoadonDAO hd = new hoadonDAO();
                hd.update(tonggia, mahd);
                
                System.out.println(tonggia+"/"+mahd);
                txttongtien1.setText(String.valueOf(tonggia));
                Showdatahd();
           } catch (Exception e) {
                System.out.println(e.getMessage());
                e.printStackTrace();
            }
        
    }//GEN-LAST:event_btnthemActionPerformed

    private void tbquanaoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbquanaoMouseClicked
        // TODO add your handling code here:
        int row = tbquanao.getSelectedRow();
        if(row >= 0)
        {
            txtmaqa.setText(tbquanao.getValueAt(row, 0).toString());
            
        }
    }//GEN-LAST:event_tbquanaoMouseClicked

    private void btntaohdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btntaohdActionPerformed
        // TODO add your handling code here:
        HoaDon hdd = new HoaDon();
        String dates = ((JTextField)txtdate.getDateEditor().getUiComponent()).getText();
        if(dates.equals("")){
            JOptionPane.showMessageDialog(this, "vui lòng chọn ngày tạo hóa đơn");
            return;
        }
        hdd.setManv(txtmanv.getText());
        System.out.println("ma nv"+txtmanv.getText());
        int row = tbkhachhang.getSelectedRow();
        if(row >= 0)
        {
            hdd.setMakh(Integer.valueOf(tbkhachhang.getValueAt(row, 0).toString()));
            System.out.println("makh:"+Integer.valueOf(tbkhachhang.getValueAt(row, 0).toString()));
        }
        hdd.setNgaytao(txtdate.getDate());
        System.out.println(txtdate.getDate());
        hoadonDAO hd = new hoadonDAO();
        try {
            hd.insert(hdd);
            JOptionPane.showMessageDialog(this, "Tạo hóa đơn thành công");
            Showdatahd();
        } catch (Exception ex) {
            System.out.println("loi"+ex);
        }
    }//GEN-LAST:event_btntaohdActionPerformed

    private void tbhoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbhoadonMouseClicked
        // TODO add your handling code here:
        
            btnxuathd.setEnabled(true);
        
        
        btntaohd.setEnabled(true);
        btnxoahd.setEnabled(true);
        try {
            int row = tbhoadon.getSelectedRow();
            if(row >= 0)
            {
                String date = tbhoadon.getValueAt(row, 4).toString();
                Date date1=new SimpleDateFormat("yyyy-MM-dd").parse(date);
                txtdate.setDate(date1);
            }
            
            
        } catch (Exception e) {
            System.out.println(e);
        }
        try {
                    
                    hoadonDAO ins = new hoadonDAO();
                    int row1 = tbhoadon.getSelectedRow();
                    if(row1 >= 0)
                    {
                        List<tthoadon> data = ins.getTT(Integer.valueOf(tbhoadon.getValueAt(row1, 2).toString()));
                        for (int i = 0; i < data.size(); i++) {
                            String makh = String.valueOf(data.get(i).getMakh());
                            txtten.setText(data.get(i).getTenkh());
                            txtdiachi.setText(data.get(i).getDiachi());
                            txtsdt.setText(data.get(i).getSdt());
                            txtmanv.setText(String.valueOf(data.get(i).getManv()));
                    }
                    }
                    
                    
                    } catch (Exception e) {
                        System.out.println(e.getMessage());
                        JOptionPane.showMessageDialog(this, "không tồn tại Khong Ton Tai");

                    }
        try {
                int row = tbhoadon.getSelectedRow();
                int mahd = Integer.valueOf(tbhoadon.getValueAt(row, 0).toString());
                cthoadonDAO ins = new cthoadonDAO();
                float tonggia = ins.getGia(mahd);
                System.out.println(tonggia+"/"+mahd);
                txttongtien1.setText(String.valueOf(tonggia));
           } catch (Exception e) {
                System.out.println(e.getMessage());
                e.printStackTrace();
            }
        Showdatacthd();
    }//GEN-LAST:event_tbhoadonMouseClicked

    private void btnxoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoaActionPerformed
        // TODO add your handling code here:
        if(txtmaqa.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui lòng nhập đủ thông tin");
            return;
        }
        try {
                quanaoDAO ins = new quanaoDAO();
                QuanAo qa = new QuanAo();
                int row = tbcthoadon.getSelectedRow();
                int maqa = Integer.valueOf(txtmaqa.getText());
                int soluongthem = Integer.valueOf(tbcthoadon.getValueAt(row, 4).toString());
                int soluongcon = ins.getsoluong(maqa);
                int soluongconlai = soluongcon + soluongthem; 
                System.out.println(soluongthem+"/"+soluongcon+"/"+soluongconlai);
                
                    ins.updatesl(soluongconlai, maqa);
                
            } catch (Exception e) {
                System.out.println(e.getMessage());
                e.printStackTrace();
            }
        try {
                ctHoaDon kh = new ctHoaDon();

                cthoadonDAO cthd = new  cthoadonDAO();
                boolean kt = cthd.delete(Integer.valueOf(txtmaqa.getText()));
                if(kt==true){
                    JOptionPane.showMessageDialog(this, "Loại bỏ thanh cong");
                }
                
                Showdatacthd();
        } catch (Exception e) {
            System.out.println(e);
        }
        try {
                int row = tbhoadon.getSelectedRow();
                int mahd = Integer.valueOf(tbhoadon.getValueAt(row, 0).toString());
                cthoadonDAO ins = new cthoadonDAO();
                float tonggia = ins.getGia(mahd);
                System.out.println(tonggia+"/"+mahd);
                txttongtien1.setText(String.valueOf(tonggia));
                hoadonDAO hd = new hoadonDAO();
                System.out.println(txttongtien1.getText() + mahd);
                hd.update(Float.valueOf(txttongtien1.getText()) ,mahd);
                Showdatahd();
           } catch (Exception e) {
                System.out.println(e.getMessage());
                e.printStackTrace();
            }
    }//GEN-LAST:event_btnxoaActionPerformed

    private void tbcthoadonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcthoadonMouseClicked
        // TODO add your handling code here:
       int row = tbcthoadon.getSelectedRow();
        if(row >= 0)
        {
            txtmaqa.setText(tbcthoadon.getValueAt(row, 1).toString());
            
        }
        
    }//GEN-LAST:event_tbcthoadonMouseClicked

    private void btnxoahdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxoahdActionPerformed
        // TODO add your handling code here:
        try {
            hoadonDAO hd = new hoadonDAO();
            int row = tbhoadon.getSelectedRow();
            if(row >= 0)
            {
                String mahd = tbhoadon.getValueAt(row, 0).toString();
                hd.delete(Integer.valueOf(mahd));
                Showdatahd();
                JOptionPane.showMessageDialog(this, "Hủy thành công");
            }
           
        } catch (Exception e) {
        }
    }//GEN-LAST:event_btnxoahdActionPerformed

    private void btnxuathdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuathdActionPerformed
        // TODO add your handling code here:
        try {
            XWPFDocument document = new XWPFDocument();
            XWPFParagraph paragraph1 = document.createParagraph();
            XWPFRun run = paragraph1.createRun();
            run.setText("Hóa Đơn Shop Quần Áo Le Le");
            XWPFParagraph paragraph = document.createParagraph();
            run = paragraph.createRun();
            run.setText("---------------------------");
            XWPFParagraph p = document.createParagraph();
            run = p.createRun();
            run.setText("Mã Nhân Viên: " + txtmanv.getText());
            
            XWPFParagraph pn = document.createParagraph();
            run = pn.createRun();
            run.setText("Khách hàng: " + txtten.getText());
            XWPFParagraph pn1 = document.createParagraph();
            run = pn1.createRun();
            run.setText("Địa chỉ: " + txtdiachi.getText());
            cthoadonDAO nv = new cthoadonDAO();
            int row1 = tbhoadon.getSelectedRow();
            if(row1 >= 0)
            {
                List<ctHoaDon> data = nv.getData(Integer.valueOf(tbhoadon.getValueAt(row1, 0).toString()));
                System.out.println(Integer.valueOf(tbhoadon.getValueAt(row1, 0).toString()));
                XWPFParagraph p4 = document.createParagraph();
                run = p4.createRun();
                run.setText("Ngày Tạo: "+ tbhoadon.getValueAt(row1, 4).toString());
                XWPFParagraph p3 = document.createParagraph();
                run = p3.createRun();
                for (int i = 0; i < data.size(); i++) {
                    XWPFParagraph p2 = document.createParagraph();
                    run = p2.createRun();                   
                    run.setText("Tên Quần Áo: "+data.get(i).getTenqa()+" |");
                    run.setText("Giá:: "+String.valueOf(data.get(i).getGia())+"VNĐ |");
                    run.setText("Số Lượng: "+String.valueOf(data.get(i).getSoluong())+" ");
                }
            }
            XWPFParagraph paragraph2 = document.createParagraph();
            run = paragraph2.createRun();
            run.setText("Tổng Tiền: "+ txttongtien1.getText()+"VNĐ");
            // Write the Document in file system
            FileOutputStream out = new FileOutputStream(new File("D://hoadon.docx"));
            document.write(out);
            out.close();
            document.close();
            JOptionPane.showMessageDialog(this, "Xuất Hóa Đơn Thành Công");
        } catch (Exception e) {
            System.out.println("loi:" + e);
        }
        
    }//GEN-LAST:event_btnxuathdActionPerformed

    private void tbcthoadonMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tbcthoadonMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_tbcthoadonMouseMoved
    public void cleardatakhachhang()
    {
        while (tbModelkhachhang.getRowCount()>0) {
            tbModelkhachhang.removeRow(0);
            
        }
    }
    private void Showdatakhachhang()
    {
        String[] tencot = {"Mã Khách Hàng", "Họ Tên", "Địa Chỉ", "Số Điện Thoai"};
        tbModelkhachhang.setColumnIdentifiers(tencot);
        tbkhachhang.setModel(tbModelkhachhang);
        cleardatakhachhang();
        khachhangDAO nv = new khachhangDAO ();
        List<KhachHang> data = nv.getKhachHang();
        for (int i = 0; i < data.size(); i++) {
            String[] row = {
                String.valueOf(data.get(i).getMakh()),
                data.get(i).getTenkh(),
                data.get(i).getDiachi(),
                data.get(i).getSodienthoai(),               
            };
            tbModelkhachhang.addRow(row);
        }
    }
    public void cleardata()
    {
        while (tbModelquanao.getRowCount()>0) {
            tbModelquanao.removeRow(0);
            
        }
    }
    private void Showdata()
    {
        String[] tencot = {"Mã Quần Áo", "Tên Quần Áo", "Hãng", "Giá"};
        tbModelquanao.setColumnIdentifiers(tencot);
        tbquanao.setModel(tbModelquanao);
        cleardata();
        quanaoDAO nv = new quanaoDAO();
        List<QuanAo> data = nv.getQuanAo();
        for (int i = 0; i < data.size(); i++) {
            String[] row = {
                String.valueOf(data.get(i).getMaqa()),
                data.get(i).getTenqa(),
                data.get(i).getHang(),
                String.valueOf(data.get(i).getGia()),
            };
            tbModelquanao.addRow(row);
        }
    }
    public void cleardatacthd()
    {
        while (tbModelcthoadon.getRowCount()>0) {
            tbModelcthoadon.removeRow(0);
            
        }
    }
    private void Showdatacthd()
    {
        String[] tencot = {"Mã Hóa Đơn", "Mã Quần Áo", "Tên Quần Áo", "Giá", "Số Lượng"};
        tbModelcthoadon.setColumnIdentifiers(tencot);
        tbcthoadon.setModel(tbModelcthoadon);
        cleardatacthd();
        cthoadonDAO nv = new cthoadonDAO();
        int row1 = tbhoadon.getSelectedRow();
        if(row1 >= 0)
        {
            List<ctHoaDon> data = nv.getData(Integer.valueOf(tbhoadon.getValueAt(row1, 0).toString()));
            System.out.println(Integer.valueOf(tbhoadon.getValueAt(row1, 0).toString()));
            for (int i = 0; i < data.size(); i++) {
            String[] row = {
                String.valueOf(data.get(i).getMahd()),
                String.valueOf(data.get(i).getMaqa()),
                data.get(i).getTenqa(),
                String.valueOf(data.get(i).getGia()),
                String.valueOf(data.get(i).getSoluong()),
            };
            tbModelcthoadon.addRow(row);
        }
        }
        
        
    }
    public void cleardatahd()
    {
        while (tbModelhoadon.getRowCount()>0) {
            tbModelhoadon.removeRow(0);
            
        }
    }
    private void Showdatahd()
    {
        String[] tencot = {"Mã Hóa Đơn", "Mã Nhân Viên", "Mã Khách Hàng", "Tổng Tiền", "Ngày Tạo"};
        tbModelhoadon.setColumnIdentifiers(tencot);
        tbhoadon.setModel(tbModelhoadon);
        cleardatahd();
        hoadonDAO nv = new hoadonDAO();
        List<HoaDon> data = nv.getHoaDon();
        System.out.println(data.size());
        for (int i = 0; i < data.size(); i++) {
            String[] row = {
                String.valueOf(data.get(i).getMahd()),
                String.valueOf(data.get(i).getManv()),
                String.valueOf(data.get(i).getMakh()),
                String.valueOf(data.get(i).getTongtien()),
                String.valueOf(data.get(i).getNgaytao())
            };
            tbModelhoadon.addRow(row);
        }
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLyHoaDon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLyHoaDon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnhuy;
    private javax.swing.JButton btntaohd;
    private javax.swing.JButton btnthem;
    private javax.swing.JComboBox<String> btntk1;
    private javax.swing.JButton btnxoa;
    private javax.swing.JButton btnxoahd;
    private javax.swing.JButton btnxuathd;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTable tbcthoadon;
    private javax.swing.JTable tbhoadon;
    private javax.swing.JTable tbkhachhang;
    private javax.swing.JTable tbquanao;
    private javax.swing.JButton tkkh;
    private javax.swing.JButton tkqa;
    private com.toedter.calendar.JDateChooser txtdate;
    private javax.swing.JLabel txtdiachi;
    private javax.swing.JLabel txtmanv;
    private javax.swing.JTextField txtmaqa;
    private javax.swing.JTextField txtqa;
    private javax.swing.JLabel txtsdt;
    private javax.swing.JTextField txtsoluong;
    private javax.swing.JLabel txtten;
    private javax.swing.JTextField txttenkh;
    private javax.swing.JLabel txttongtien;
    private javax.swing.JLabel txttongtien1;
    // End of variables declaration//GEN-END:variables
}
