/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package quanlyshop;

import DAO.hoadonDAO;
import java.io.File;
import java.io.FileOutputStream;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.table.DefaultTableModel;
import model.HoaDon;
import org.apache.poi.ss.usermodel.Cell;
import org.apache.poi.ss.usermodel.CellType;
import org.apache.poi.xssf.usermodel.XSSFRow;
import org.apache.poi.xssf.usermodel.XSSFSheet;
import org.apache.poi.xssf.usermodel.XSSFWorkbook;

/**
 *
 * @author ADMIN
 */
public class ThongKe extends javax.swing.JFrame {

    /**
     * Creates new form QuanLyThongKe
     */
    private final DefaultTableModel tbModelhoadon = new DefaultTableModel();
    public ThongKe() {
        initComponents();
        Showdatahd();
        txtbatdau.setDateFormatString("yyyy/MM/dd");
        txtkt.setDateFormatString("yyyy/MM/dd");
        hoadonDAO hd = new hoadonDAO();
        txttongtien.setText(String.valueOf(hd.tongtien()));
    }
    public void cleardatahd()
    {
        while (tbModelhoadon.getRowCount()>0) {
            tbModelhoadon.removeRow(0);
            
        }
    }
    private void Showdatahd()
    {
        String[] tencot = {"Mã Hóa Đơn", "Mã Nhân Viên", "Mã Khách Hàng", "Tổng Tiền", "Ngày Tạo"};
        tbModelhoadon.setColumnIdentifiers(tencot);
        tbhoadon.setModel(tbModelhoadon);
        cleardatahd();
        hoadonDAO nv = new hoadonDAO();
        List<HoaDon> data = nv.getHoaDon();
        System.out.println(data.size());
        for (int i = 0; i < data.size(); i++) {
            String[] row = {
                String.valueOf(data.get(i).getMahd()),
                String.valueOf(data.get(i).getManv()),
                String.valueOf(data.get(i).getMakh()),
                String.valueOf(data.get(i).getTongtien()),
                String.valueOf(data.get(i).getNgaytao())
            };
            tbModelhoadon.addRow(row);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtkt = new com.toedter.calendar.JDateChooser();
        txtbatdau = new com.toedter.calendar.JDateChooser();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        btnxuat = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbhoadon = new javax.swing.JTable();
        btnthongke = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txttongtien = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtbatdau.setMinSelectableDate(new java.util.Date(-62135791128000L));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("Thống Kê");

        jLabel2.setText("Từ ngày");

        jLabel3.setText("Đến ngày");

        btnxuat.setText("Xuất Exel");
        btnxuat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnxuatActionPerformed(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Danh sách  hóa đơn"));

        tbhoadon.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(tbhoadon);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 531, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 241, Short.MAX_VALUE)
                .addContainerGap())
        );

        btnthongke.setText("Thống kê");
        btnthongke.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnthongkeActionPerformed(evt);
            }
        });

        jLabel4.setText("Tổng Doanh Thu:");

        txttongtien.setText("....");

        jLabel6.setText("VNĐ");

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/back-icon.png"))); // NOI18N
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(187, 187, 187)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(txttongtien, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addGap(303, 303, 303))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 58, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(txtbatdau, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(192, 192, 192)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtkt, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(25, 25, 25)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(162, 162, 162))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(btnthongke)
                                .addGap(84, 84, 84)
                                .addComponent(btnxuat)
                                .addGap(232, 232, 232))))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(16, 16, 16)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(txtbatdau, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtkt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(txttongtien)
                            .addComponent(jLabel6)))
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnxuat)
                    .addComponent(btnthongke))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnthongkeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnthongkeActionPerformed
        // TODO add your handling code here:
        try {
//            String pattern = "MM-dd-yyyy";
//            SimpleDateFormat simpleDateFormat = new SimpleDateFormat(pattern);
            hoadonDAO hd = new hoadonDAO();
            String dates = ((JTextField)txtbatdau.getDateEditor().getUiComponent()).getText();
            String datee = ((JTextField)txtkt.getDateEditor().getUiComponent()).getText();
            System.out.println(dates);
            if(dates.equals("") || datee.equals("")){
                JOptionPane.showMessageDialog(this, "Vui lòng chọn khoảng thời gian");
                return;
            }
            List<HoaDon> data=hd.getHoaDonBYEDATE(dates,datee);
            cleardatahd();
            for (int i = 0; i < data.size(); i++) {
                String[] row = {
                    String.valueOf(data.get(i).getMahd()),
                    String.valueOf(data.get(i).getManv()),
                    String.valueOf(data.get(i).getMakh()),
                    String.valueOf(data.get(i).getTongtien()),
                    String.valueOf(data.get(i).getNgaytao())
                };
                tbModelhoadon.addRow(row);
            }
            txttongtien.setText(String.valueOf(hd.tongtienBYEDATE(dates, datee)));
        } catch (Exception e) {
            System.out.println(e);
        }
        
    }//GEN-LAST:event_btnthongkeActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        // TODO add your handling code here:
        this.setVisible(false);
        HeThong ht = new HeThong();
        ht.setLocationRelativeTo(null);
        ht.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void btnxuatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnxuatActionPerformed
        // TODO add your handling code here:
        
        try {
            XSSFWorkbook wb = new XSSFWorkbook();
            XSSFSheet sh = wb.createSheet("danh sach");
            XSSFRow row = null;
            Cell cell = null;
            row=sh.createRow(0);
            cell= row.createCell(0, CellType.STRING);
            cell.setCellValue("Mã Hóa Đơn");
            cell= row.createCell(1, CellType.STRING);
            cell.setCellValue("Mã Nhân Viên");
            cell= row.createCell(2, CellType.STRING);
            cell.setCellValue("Mã Khách Hàng");
            cell= row.createCell(3, CellType.STRING);
            cell.setCellValue("Mã Tổng Tiền");
            cell= row.createCell(4, CellType.STRING);
            cell.setCellValue("Mã Ngày Tạo");
            
            hoadonDAO hd = new hoadonDAO();
            String dates = ((JTextField)txtbatdau.getDateEditor().getUiComponent()).getText();
            String datee = ((JTextField)txtkt.getDateEditor().getUiComponent()).getText();
            if(dates.equals("") || datee.equals("")){
                List<HoaDon> data=hd.getHoaDon();
                cleardatahd();
                int k =0;
                for (int i = 0; i < data.size(); i++) {
                    row=sh.createRow(1+i);
                    cell = row.createCell(0,CellType.NUMERIC);
                    cell.setCellValue(data.get(i).getMahd()); 
                    cell = row.createCell(1,CellType.NUMERIC);
                    cell.setCellValue(data.get(i).getManv());
                    cell = row.createCell(2,CellType.NUMERIC);
                    cell.setCellValue(data.get(i).getMakh());
                    cell = row.createCell(3,CellType.NUMERIC);
                    cell.setCellValue(data.get(i).getTongtien());
                    cell = row.createCell(4,CellType.STRING);
                    cell.setCellValue(data.get(i).getNgaytao());
                    k++;
                }

                row=sh.createRow(k+1);
                cell= row.createCell(0, CellType.NUMERIC);
                cell.setCellValue("Tổng Thu Nhập:"+txttongtien.getText() + "VND");
            }else{
                List<HoaDon> data=hd.getHoaDonBYEDATE(dates,datee);
                cleardatahd();
                int k =0;
                for (int i = 0; i < data.size(); i++) {
                    row=sh.createRow(1+i);
                    cell = row.createCell(0,CellType.NUMERIC);
                    cell.setCellValue(data.get(i).getMahd()); 
                    cell = row.createCell(1,CellType.NUMERIC);
                    cell.setCellValue(data.get(i).getManv());
                    cell = row.createCell(2,CellType.NUMERIC);
                    cell.setCellValue(data.get(i).getMakh());
                    cell = row.createCell(3,CellType.NUMERIC);
                    cell.setCellValue(data.get(i).getTongtien());
                    cell = row.createCell(4,CellType.STRING);
                    cell.setCellValue(data.get(i).getNgaytao());
                    k++;
                }

                row=sh.createRow(k+1);
                cell= row.createCell(0, CellType.NUMERIC);
                cell.setCellValue("Tổng Thu Nhập:"+String.valueOf(hd.tongtienBYEDATE(dates, datee)) + "VND");
            }
           
            
            
            File f = new File("D://danhsach.xlsx");
            try {
                    FileOutputStream fis = new FileOutputStream(f);
                    wb.write(fis);
                    fis.close();
                    JOptionPane.showMessageDialog(this, "Xuất Thống Kê Thành Công");
            } catch (Exception e) {
                  System.out.println(e);
            }
            Showdatahd();
        } catch (Exception e) {
            System.out.println(e);
        }
    }//GEN-LAST:event_btnxuatActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThongKe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThongKe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnthongke;
    private javax.swing.JButton btnxuat;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tbhoadon;
    private com.toedter.calendar.JDateChooser txtbatdau;
    private com.toedter.calendar.JDateChooser txtkt;
    private javax.swing.JLabel txttongtien;
    // End of variables declaration//GEN-END:variables
}
